### PR TITLE
Convert to Swift 3

### PR DESCRIPTION
**Pull request by danysousa**
Convertion to swift 3
Use swift 3 dependencies.
Tests : Ok

### CODE REVIEW

**Comment by eliburke** [comment]
@danysousa Why did you decide to switch from [Any] back to [AnyObject]? 
I'm just curious.

**Comment by wybie-lovat** [comment]
Hey @danysousa thanks for the PR! I will merge this as soon as I understand all implications on Cocoapods and library versioning. If you want, I'll be glad to discuss those issues with you - Email me your Skype to yo.ab[AT]outlook.com

**Comment by danysousa** [comment]
Hi ! @eliburke In my first conversion to swift 3, I tried to change the SwampMessage Protocol from 

``` swift
protocol SwampMessage {
    init(payload: [AnyObject])
    func marshal() -> [AnyObject]
}
```

to 

``` swift
protocol SwampMessage {
    init(payload: [Any])
    func marshal() -> [Any]
}
```

because all implementation of marshal function of this protocol try to append List, Int, String, ... in a [AnyObject], but in Swift 3 this types is no longer "magically" bridges with the ObjC equivalent.
So in my first try, I change to Any for this reason.

After reflexion, it's not my own code, AnyObject is more specific than Any, and I can't be sure that "Any" have no impact, so I roll back to AnyObject and I add (a lot of) `as` in implementations.

**Comment by eliburke** [comment]
@danysousa Ahhhh cool. Thanks for the explanation. Prior to noticing your PR I had just finished my own fork and was preparing a PR for it. I did the opposite, starting with [AnyObject] and switching to [Any] because it seemed easier. 😮

**Comment by elliottwilliams** [comment]
@danysousa @eliburke I'm wondering if keeping `AnyObject` is really necessary...it makes for some ugly code (explicitly casting bridged value types like `String` and `Array` to `AnyObject`, for example), and it could lower performance by having to box value types in the heap.

Take a look at the [proposal that switched `AnyObject` to `Any`](https://github.com/apple/swift-evolution/blob/master/proposals/0116-id-as-any.md#universal-bridging-conversion-into-objective-c-id). Under Swift 2, bridged value types were implicitly boxed/unboxed to their respective value types. Similarly, unabridged value types (custom value types) used to be unboxed in Swift code by casting `AnyObject` to a value type. In both cases, using `Any` continues to unbox such values, but the boxing/unboxing is done by the compiler, not the source code.

So while I'm not too familiar with Swamp itself (I've been wanting to contribute soon!) I don't see why `Any` would be a problem here. Thoughts?

**Comment by eliburke** [comment]
@elliottwilliams this level of discussion is pretty far outside my comfort zone, but if I understand you correctly, using `AnyObject` means that all of the native Swift data types are converted to NSString, NSNumber, etc. Using `Any` keeps them them as native data types (especially important for Array and Dictionary which are not classes per [this article](http://en.swifter.tips/any-anyobject/)

**Comment by danysousa** [comment]
@eliburke @elliottwilliams I'm agree with @elliottwilliams `Any` should be not a problem here and we need to keep optimized code.

In fact, with `Any` or `AnyObject` the unit test succeeded.

I keep the version with Any in my master branch [here](https://github.com/danysousa/swamp)
@iscriptology It's ok for you ?

**Comment by eliburke** [comment]
@iscriptology I'm adding MsgPack support to SWAMP, and it goes much better with `Any` than `AnyObject`. Just sayin, in case you need more reasons to pick one or the other. 😄 

Either way, I can submit a PR once this one has been merged one way or the other.

**Comment by wybie-lovat** [comment]
@danysousa can you make a PR from your master branch with the Any-instead-of-AnyObject? I'm now reviewing the master branch and hopefully merge it soon. Versioning will be 0.2.x for swift 3 I guess.
@eliburke MsgPack will be great! I couldn't actually be sure how to determine the server's serialization support, hope you'll figure that out.
@elliottwilliams waiting for your contributions too :)

**Comment by wybie-lovat** [comment]
@danysousa When testing iOS it worked just fine. Good job! But when building Swamp-OSX it shows this error:
screen shot 2016-10-15 at 15 53 37
have you encountered this?
(I'm building your master branch)

**Comment by danysousa** [comment]
@iscriptology Yes I just push latest changes, can you pull and try again ?
I have created the pull request :)

**Pull request closed without merging**
